apiVersion: vendir.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.12.0
directories:
- path: config/upstream
  contents:
  - path: vsphere-csi
    git:
      url: git@github.com:kubernetes-sigs/vsphere-csi-driver.git
      ref: cf84f1a0b5cf897099587efd6d0b33866935211c
    includePaths:
      - manifests/vanilla/vsphere-csi-driver.yaml
